### ISSUE TITLE
Replace Goerli with Sepolia

### ISSUE THREAD

**Issue by roo-shy** [Consensys/ape-linea#5]
### Elevator pitch:

Please replace goerli with sepolia option to `ape-linea/ape-config.yaml.example`

```
geth:
  linea:
    goerli:
      uri: https://linea-goerli.infura.io/v3/<YOUR-PROJECT-ID>
    mainnet:
      uri: https://linea-mainnet.infura.io/v3/<YOUR-PROJECT-ID>
```

and when installing: 

```
ape console --network linea:goerli
ape console --network linea:mainnet
```

### Value:

everyone using Ape Framework on testnet
